/// <copyright company="JetBrains">
/// Copyright © 2003-2008 JetBrains s.r.o.
/// You may distribute under the terms of the GNU General Public License, as published by the Free Software Foundation, version 2 (see License.txt in the repository root folder).
/// </copyright>

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace PostToConfluence.com.atlassian.confluence {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConfluenceSoapService", Namespace="http://www.atlassian.com/software/confluence/$Proxy26/")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemotePageHistory))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteComment))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteAttachment))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteLock))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AbstractRemotePageSummary))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteSpaceSummary))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteSearchResult))]
    public class ConfluenceSoap : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ConfluenceSoap() {
            this.Url = "http://confluence.atlassian.com/rpc/soap/confluenceservice-v1";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getPermissions", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string[] getPermissions(string arg0, string arg1) {
            object[] results = this.Invoke("getPermissions", new object[] {
                        arg0,
                        arg1});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPermissions(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPermissions", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetPermissions(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("search", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemoteSearchResult[] search(string arg0, string arg1, int arg2) {
            object[] results = this.Invoke("search", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((RemoteSearchResult[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsearch(string arg0, string arg1, int arg2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("search", new object[] {
                        arg0,
                        arg1,
                        arg2}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemoteSearchResult[] Endsearch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemoteSearchResult[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="search1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("search", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemoteSearchResult[] search(string arg0, string arg1, Map arg2, int arg3) {
            object[] results = this.Invoke("search1", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3});
            return ((RemoteSearchResult[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsearch1(string arg0, string arg1, Map arg2, int arg3, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("search1", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemoteSearchResult[] Endsearch1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemoteSearchResult[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getUser", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemoteUser getUser(string arg0, string arg1) {
            object[] results = this.Invoke("getUser", new object[] {
                        arg0,
                        arg1});
            return ((RemoteUser)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetUser(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getUser", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemoteUser EndgetUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemoteUser)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getGroups", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string[] getGroups(string arg0) {
            object[] results = this.Invoke("getGroups", new object[] {
                        arg0});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetGroups(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getGroups", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetGroups(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("login", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string login(string arg0, string arg1) {
            object[] results = this.Invoke("login", new object[] {
                        arg0,
                        arg1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginlogin(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("login", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endlogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getServerInfo", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemoteServerInfo getServerInfo(string arg0) {
            object[] results = this.Invoke("getServerInfo", new object[] {
                        arg0});
            return ((RemoteServerInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetServerInfo(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getServerInfo", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemoteServerInfo EndgetServerInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemoteServerInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("addUser", RequestNamespace="x", ResponseNamespace="x")]
        public void addUser(string arg0, RemoteUser arg1, string arg2) {
            this.Invoke("addUser", new object[] {
                        arg0,
                        arg1,
                        arg2});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginaddUser(string arg0, RemoteUser arg1, string arg2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("addUser", new object[] {
                        arg0,
                        arg1,
                        arg2}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndaddUser(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("addGroup", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public bool addGroup(string arg0, string arg1) {
            object[] results = this.Invoke("addGroup", new object[] {
                        arg0,
                        arg1});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginaddGroup(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("addGroup", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndaddGroup(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getSpace", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemoteSpace getSpace(string arg0, string arg1) {
            object[] results = this.Invoke("getSpace", new object[] {
                        arg0,
                        arg1});
            return ((RemoteSpace)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSpace(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSpace", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemoteSpace EndgetSpace(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemoteSpace)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("removeSpace", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public bool removeSpace(string arg0, string arg1) {
            object[] results = this.Invoke("removeSpace", new object[] {
                        arg0,
                        arg1});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginremoveSpace(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("removeSpace", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndremoveSpace(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getSpaces", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemoteSpaceSummary[] getSpaces(string arg0) {
            object[] results = this.Invoke("getSpaces", new object[] {
                        arg0});
            return ((RemoteSpaceSummary[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSpaces(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSpaces", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemoteSpaceSummary[] EndgetSpaces(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemoteSpaceSummary[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getPage", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemotePage getPage(string arg0, long arg1) {
            object[] results = this.Invoke("getPage", new object[] {
                        arg0,
                        arg1});
            return ((RemotePage)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPage(string arg0, long arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPage", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemotePage EndgetPage(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemotePage)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="getPage1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getPage", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemotePage getPage(string arg0, string arg1, string arg2) {
            object[] results = this.Invoke("getPage1", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((RemotePage)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPage1(string arg0, string arg1, string arg2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPage1", new object[] {
                        arg0,
                        arg1,
                        arg2}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemotePage EndgetPage1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemotePage)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getLocks", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemoteLock[] getLocks(string arg0, long arg1) {
            object[] results = this.Invoke("getLocks", new object[] {
                        arg0,
                        arg1});
            return ((RemoteLock[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetLocks(string arg0, long arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLocks", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemoteLock[] EndgetLocks(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemoteLock[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getAttachments", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemoteAttachment[] getAttachments(string arg0, long arg1) {
            object[] results = this.Invoke("getAttachments", new object[] {
                        arg0,
                        arg1});
            return ((RemoteAttachment[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAttachments(string arg0, long arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAttachments", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemoteAttachment[] EndgetAttachments(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemoteAttachment[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getComments", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemoteComment[] getComments(string arg0, long arg1) {
            object[] results = this.Invoke("getComments", new object[] {
                        arg0,
                        arg1});
            return ((RemoteComment[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetComments(string arg0, long arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getComments", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemoteComment[] EndgetComments(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemoteComment[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getPages", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemotePageSummary[] getPages(string arg0, string arg1) {
            object[] results = this.Invoke("getPages", new object[] {
                        arg0,
                        arg1});
            return ((RemotePageSummary[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPages(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPages", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemotePageSummary[] EndgetPages(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemotePageSummary[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("logout", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public bool logout(string arg0) {
            object[] results = this.Invoke("logout", new object[] {
                        arg0});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginlogout(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("logout", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool Endlogout(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getBlogEntries", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemoteBlogEntrySummary[] getBlogEntries(string arg0, string arg1) {
            object[] results = this.Invoke("getBlogEntries", new object[] {
                        arg0,
                        arg1});
            return ((RemoteBlogEntrySummary[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetBlogEntries(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getBlogEntries", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemoteBlogEntrySummary[] EndgetBlogEntries(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemoteBlogEntrySummary[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getBlogEntry", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemoteBlogEntry getBlogEntry(string arg0, long arg1) {
            object[] results = this.Invoke("getBlogEntry", new object[] {
                        arg0,
                        arg1});
            return ((RemoteBlogEntry)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetBlogEntry(string arg0, long arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getBlogEntry", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemoteBlogEntry EndgetBlogEntry(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemoteBlogEntry)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getPageHistory", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemotePageHistory[] getPageHistory(string arg0, long arg1) {
            object[] results = this.Invoke("getPageHistory", new object[] {
                        arg0,
                        arg1});
            return ((RemotePageHistory[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPageHistory(string arg0, long arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPageHistory", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemotePageHistory[] EndgetPageHistory(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemotePageHistory[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("renderContent", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string renderContent(string arg0, string arg1, long arg2, string arg3, Map arg4) {
            object[] results = this.Invoke("renderContent", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginrenderContent(string arg0, string arg1, long arg2, string arg3, Map arg4, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("renderContent", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndrenderContent(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="renderContent1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("renderContent", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string renderContent(string arg0, string arg1, long arg2, string arg3) {
            object[] results = this.Invoke("renderContent1", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginrenderContent1(string arg0, string arg1, long arg2, string arg3, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("renderContent1", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndrenderContent1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("deletePage", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public bool deletePage(string arg0, long arg1) {
            object[] results = this.Invoke("deletePage", new object[] {
                        arg0,
                        arg1});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindeletePage(string arg0, long arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("deletePage", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EnddeletePage(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("storeBlogEntry", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemoteBlogEntry storeBlogEntry(string arg0, RemoteBlogEntry arg1) {
            object[] results = this.Invoke("storeBlogEntry", new object[] {
                        arg0,
                        arg1});
            return ((RemoteBlogEntry)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginstoreBlogEntry(string arg0, RemoteBlogEntry arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("storeBlogEntry", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemoteBlogEntry EndstoreBlogEntry(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemoteBlogEntry)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("storePage", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemotePage storePage(string arg0, RemotePage arg1) {
            object[] results = this.Invoke("storePage", new object[] {
                        arg0,
                        arg1});
            return ((RemotePage)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginstorePage(string arg0, RemotePage arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("storePage", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemotePage EndstorePage(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemotePage)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getUserGroups", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string[] getUserGroups(string arg0, string arg1) {
            object[] results = this.Invoke("getUserGroups", new object[] {
                        arg0,
                        arg1});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetUserGroups(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getUserGroups", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetUserGroups(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("addUserToGroup", RequestNamespace="x", ResponseNamespace="x")]
        public void addUserToGroup(string arg0, string arg1, string arg2) {
            this.Invoke("addUserToGroup", new object[] {
                        arg0,
                        arg1,
                        arg2});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginaddUserToGroup(string arg0, string arg1, string arg2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("addUserToGroup", new object[] {
                        arg0,
                        arg1,
                        arg2}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndaddUserToGroup(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("addSpace", RequestNamespace="x", ResponseNamespace="x")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public RemoteSpace addSpace(string arg0, RemoteSpace arg1) {
            object[] results = this.Invoke("addSpace", new object[] {
                        arg0,
                        arg1});
            return ((RemoteSpace)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginaddSpace(string arg0, RemoteSpace arg1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("addSpace", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }
        
        /// <remarks/>
        public RemoteSpace EndaddSpace(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RemoteSpace)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("RemoteSearchResult", "http://www.atlassian.com/package/com.atlassian.confluence.rpc.soap.beans/")]
    public class RemoteSearchResult {
        
        /// <remarks/>
        public string type;
        
        /// <remarks/>
        public long id;
        
        /// <remarks/>
        public string title;
        
        /// <remarks/>
        public string url;
        
        /// <remarks/>
        public string excerpt;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("RemotePageHistory", "http://www.atlassian.com/package/com.atlassian.confluence.rpc.soap.beans/")]
    public class RemotePageHistory {
        
        /// <remarks/>
        public long id;
        
        /// <remarks/>
        public int version;
        
        /// <remarks/>
        public string modifier;
        
        /// <remarks/>
        public System.DateTime modified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("RemoteComment", "http://www.atlassian.com/package/com.atlassian.confluence.rpc.soap.beans/")]
    public class RemoteComment {
        
        /// <remarks/>
        public long id;
        
        /// <remarks/>
        public long pageId;
        
        /// <remarks/>
        public System.DateTime created;
        
        /// <remarks/>
        public string title;
        
        /// <remarks/>
        public string url;
        
        /// <remarks/>
        public string creator;
        
        /// <remarks/>
        public string content;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("RemoteAttachment", "http://www.atlassian.com/package/com.atlassian.confluence.rpc.soap.beans/")]
    public class RemoteAttachment {
        
        /// <remarks/>
        public long id;
        
        /// <remarks/>
        public long pageId;
        
        /// <remarks/>
        public long fileSize;
        
        /// <remarks/>
        public string title;
        
        /// <remarks/>
        public string fileName;
        
        /// <remarks/>
        public string contentType;
        
        /// <remarks/>
        public string creator;
        
        /// <remarks/>
        public string url;
        
        /// <remarks/>
        public System.DateTime created;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("RemoteLock", "http://www.atlassian.com/package/com.atlassian.confluence.rpc.soap.beans/")]
    public class RemoteLock {
        
        /// <remarks/>
        public string lockType;
        
        /// <remarks/>
        public string lockedBy;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("AbstractRemotePageSummary", "http://www.atlassian.com/package/com.atlassian.confluence.rpc.soap.beans/")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteBlogEntrySummary))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteBlogEntry))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemotePageSummary))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemotePage))]
    public abstract class AbstractRemotePageSummary {
        
        /// <remarks/>
        public long id;
        
        /// <remarks/>
        public string space;
        
        /// <remarks/>
        public string title;
        
        /// <remarks/>
        public string url;
        
        /// <remarks/>
        public int locks;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("RemoteBlogEntrySummary", "http://www.atlassian.com/package/com.atlassian.confluence.rpc.soap.beans/")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteBlogEntry))]
    public class RemoteBlogEntrySummary : AbstractRemotePageSummary {
        
        /// <remarks/>
        public System.DateTime publishDate;
        
        /// <remarks/>
        public string author;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("RemoteBlogEntry", "http://www.atlassian.com/package/com.atlassian.confluence.rpc.soap.beans/")]
    public class RemoteBlogEntry : RemoteBlogEntrySummary {
        
        /// <remarks/>
        public string content;
        
        /// <remarks/>
        public int version;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("RemotePageSummary", "http://www.atlassian.com/package/com.atlassian.confluence.rpc.soap.beans/")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemotePage))]
    public class RemotePageSummary : AbstractRemotePageSummary {
        
        /// <remarks/>
        public long parentId;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("RemotePage", "http://www.atlassian.com/package/com.atlassian.confluence.rpc.soap.beans/")]
    public class RemotePage : RemotePageSummary {
        
        /// <remarks/>
        public System.DateTime created;
        
        /// <remarks/>
        public System.DateTime modified;
        
        /// <remarks/>
        public string creator;
        
        /// <remarks/>
        public string modifier;
        
        /// <remarks/>
        public string content;
        
        /// <remarks/>
        public int version;
        
        /// <remarks/>
        public bool homePage;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("RemoteSpaceSummary", "http://www.atlassian.com/package/com.atlassian.confluence.rpc.soap.beans/")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteSpace))]
    public class RemoteSpaceSummary {
        
        /// <remarks/>
        public string key;
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public string url;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("RemoteSpace", "http://www.atlassian.com/package/com.atlassian.confluence.rpc.soap.beans/")]
    public class RemoteSpace : RemoteSpaceSummary {
        
        /// <remarks/>
        public string description;
        
        /// <remarks/>
        public long homePage;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("RemoteServerInfo", "http://www.atlassian.com/package/com.atlassian.confluence.rpc.soap.beans/")]
    public class RemoteServerInfo {
        
        /// <remarks/>
        public int majorVersion;
        
        /// <remarks/>
        public int minorVersion;
        
        /// <remarks/>
        public int patchLevel;
        
        /// <remarks/>
        public bool developmentBuild;
        
        /// <remarks/>
        public string buildId;
        
        /// <remarks/>
        public string baseUrl;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("RemoteUser", "http://www.atlassian.com/package/com.atlassian.confluence.rpc.soap.beans/")]
    public class RemoteUser {
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public string fullname;
        
        /// <remarks/>
        public string email;
        
        /// <remarks/>
        public string url;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("Map", "http://www.atlassian.com/package/java.util/")]
    public abstract class Map {
    }
}
