//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1158.0 using the following command:
// xscgen --namespace JetBrains.Build.InstallationData --collectionSettersMode PublicWithoutConstructorInitialization --collectionType System.Array --pcl G:\Projects\omea\Src\Core\OmniaMeaBase\Install\InstallationData.xsd
namespace JetBrains.Build.InstallationData
{
    
    
    /// <summary>
    /// <para>The root element for the file.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1158.0")]
    [System.Xml.Serialization.XmlTypeAttribute("InstallationDataXml", Namespace="urn:shemas-jetbrains-com:installation-data")]
    [System.Xml.Serialization.XmlRootAttribute("InstallationData", Namespace="urn:shemas-jetbrains-com:installation-data")]
    public partial class InstallationDataXml
    {
        
        /// <summary>
        /// <para>The root element for all the Registry keys and values.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Registry")]
        public RegistryXml Registry { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private FolderXml[] _files;
        
        /// <summary>
        /// <para>The root elements for all the satellite files (but for the product binaries) included with the installations.</para>
        /// </summary>
        [System.Xml.Serialization.XmlArrayAttribute("Files")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Folder", Namespace="urn:shemas-jetbrains-com:installation-data")]
        public FolderXml[] Files
        {
            get
            {
                return _files;
            }
            set
            {
                _files = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1158.0")]
    [System.Xml.Serialization.XmlTypeAttribute("RegistryXml", Namespace="urn:shemas-jetbrains-com:installation-data")]
    public partial class RegistryXml
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private RegistryKeyXml[] _key;
        
        [System.Xml.Serialization.XmlElementAttribute("Key")]
        public RegistryKeyXml[] Key
        {
            get
            {
                return _key;
            }
            set
            {
                _key = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Key collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KeySpecified
        {
            get
            {
                return ((this.Key != null) 
                            && (this.Key.Length != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private RegistryValueXml[] _value;
        
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public RegistryValueXml[] Value
        {
            get
            {
                return _value;
            }
            set
            {
                _value = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Value collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified
        {
            get
            {
                return ((this.Value != null) 
                            && (this.Value.Length != 0));
            }
        }
    }
    
    /// <summary>
    /// <para>Represents a Registry key. You should create the Key elements only for those Registry keys that should be deleted upon uninstallation.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1158.0")]
    [System.Xml.Serialization.XmlTypeAttribute("RegistryKeyXml", Namespace="urn:shemas-jetbrains-com:installation-data")]
    public partial class RegistryKeyXml : RegistryBaseXml
    {
    }
    
    /// <summary>
    /// <para>Base type that holds the attributes that are common for both keys and values.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1158.0")]
    [System.Xml.Serialization.XmlTypeAttribute("RegistryBaseXml", Namespace="urn:shemas-jetbrains-com:installation-data")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistryKeyXml))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistryValueXml))]
    public partial class RegistryBaseXml
    {
        
        /// <summary>
        /// <para>The Registry hive into which the key or value should be written.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Hive")]
        public RegistryHiveXml Hive { get; set; }
        
        /// <summary>
        /// <para>Relative path to the key under the hive, not including any leading or trailing slahes.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Key")]
        public string Key { get; set; }
    }
    
    /// <summary>
    /// <para>A choice of the Registry hives to write into.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1158.0")]
    [System.Xml.Serialization.XmlTypeAttribute("RegistryHiveXml", Namespace="urn:shemas-jetbrains-com:installation-data")]
    public enum RegistryHiveXml
    {
        
        /// <summary>
        /// <para>HKEY_CLASSES_ROOT.</para>
        /// </summary>
        Hkcr,
        
        /// <summary>
        /// <para>HKEY_LOCAL_MACHINE.</para>
        /// </summary>
        Hklm,
        
        /// <summary>
        /// <para>HKEY_CURRENT_USER.</para>
        /// </summary>
        Hkcu,
        
        /// <summary>
        /// <para>Either HKEY_LOCAL_MACHINE or HKEY_CURRENT_USER, depending on the installation type (“ALLUSERS” installer property value).</para>
        /// </summary>
        Hkmu,
    }
    
    /// <summary>
    /// <para>Represents a value to be written to the Registry. On uninstallation, the value will be deleted. It is not necessary to have a key element for each value, unless you want it to be deleted upon uninstallation.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1158.0")]
    [System.Xml.Serialization.XmlTypeAttribute("RegistryValueXml", Namespace="urn:shemas-jetbrains-com:installation-data")]
    public partial class RegistryValueXml : RegistryBaseXml
    {
        
        /// <summary>
        /// <para>Name of the value under its key, or an empty string for the default value of the key.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Name")]
        public string Name { get; set; }
        
        /// <summary>
        /// <para>Value for the value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Value")]
        public string Value { get; set; }
        
        /// <summary>
        /// <para>Type of the value, which determines the type of the Windows Registry value to be created. The Value must be formatted accordingly.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Type")]
        public RegistryValueTypeXml Type { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _permanent = false;
        
        /// <summary>
        /// <para>Specifies that the value should be written on registration and left intact on unregistration.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("Permanent")]
        public bool Permanent
        {
            get
            {
                return _permanent;
            }
            set
            {
                _permanent = value;
            }
        }
    }
    
    /// <summary>
    /// <para>Lists possible types for the Registry values.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1158.0")]
    [System.Xml.Serialization.XmlTypeAttribute("RegistryValueTypeXml", Namespace="urn:shemas-jetbrains-com:installation-data")]
    public enum RegistryValueTypeXml
    {
        
        /// <summary>
        /// <para>An integer DWORD value.</para>
        /// </summary>
        Dword,
        
        /// <summary>
        /// <para>A string value.</para>
        /// </summary>
        String,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1158.0")]
    [System.Xml.Serialization.XmlTypeAttribute("FilesXml", Namespace="urn:shemas-jetbrains-com:installation-data")]
    public partial class FilesXml
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private FolderXml[] _folder;
        
        /// <summary>
        /// <para>A collection of files under the same folder (both on the source and target systems).</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Folder")]
        public FolderXml[] Folder
        {
            get
            {
                return _folder;
            }
            set
            {
                _folder = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1158.0")]
    [System.Xml.Serialization.XmlTypeAttribute("FolderXml", Namespace="urn:shemas-jetbrains-com:installation-data")]
    public partial class FolderXml
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private FileXml[] _files;
        
        [System.Xml.Serialization.XmlArrayAttribute("Files")]
        [System.Xml.Serialization.XmlArrayItemAttribute("File", Namespace="urn:shemas-jetbrains-com:installation-data")]
        public FileXml[] Files
        {
            get
            {
                return _files;
            }
            set
            {
                _files = value;
            }
        }
        
        /// <summary>
        /// <para>An ID for this folder entry, from which the component, folder and file IDs in the installation database are derived.</para>
        /// <para>Defines an ID so that it were directly mappable into a programming language identifier.</para>
        /// <para xml:lang="en">Pattern: [A-Za-z_][A-Za-z_0-9]*.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("Id")]
        public string Id { get; set; }
        
        /// <summary>
        /// <para>One of the root folders to locate the file on the source system.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("SourceRoot")]
        public SourceRootXml SourceRoot { get; set; }
        
        /// <summary>
        /// <para>Relative path from the specified root to the directory on the source system.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("SourceDir")]
        public string SourceDir { get; set; }
        
        /// <summary>
        /// <para>One of the root folders to locate the file on the target system.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("TargetRoot")]
        public TargetRootXml TargetRoot { get; set; }
        
        /// <summary>
        /// <para>Relative path from the specified root to the directory on the target system.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("TargetDir")]
        public string TargetDir { get; set; }
        
        /// <summary>
        /// <para>GUID for the component to be generated in the installer.</para>
        /// <para>An all-uppercase curlies-enclosed GUID.</para>
        /// <para xml:lang="en">Pattern: \{[0-9A-Z]{8}-[0-9A-Z]{4}-[0-9A-Z]{4}-[0-9A-Z]{4}-[0-9A-Z]{12}\}.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("MsiComponentGuid")]
        public string MsiComponentGuid { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1158.0")]
    [System.Xml.Serialization.XmlTypeAttribute("FolderXmlFiles", Namespace="urn:shemas-jetbrains-com:installation-data", AnonymousType=true)]
    public partial class FolderXmlFiles
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private FileXml[] _file;
        
        /// <summary>
        /// <para>A single satellite file in the installation.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("File")]
        public FileXml[] File
        {
            get
            {
                return _file;
            }
            set
            {
                _file = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1158.0")]
    [System.Xml.Serialization.XmlTypeAttribute("FileXml", Namespace="urn:shemas-jetbrains-com:installation-data")]
    public partial class FileXml
    {
        
        /// <summary>
        /// <para>The local name of the file on the source system. May be a mask that matches more than one file.</para>
        /// <para>A local file name must not contain slashes.</para>
        /// <para xml:lang="en">Pattern: [^\\/\?\:]+.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("SourceName")]
        public string SourceName { get; set; }
        
        /// <summary>
        /// <para>The local name of the file on the target system. If left empty, will be the same as the source name. Must be left empty if the source name matches more than one file.</para>
        /// <para>A local file name must not contain slashes.</para>
        /// <para xml:lang="en">Pattern: [^\\/\?\:]+.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("TargetName")]
        public string TargetName { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1158.0")]
    [System.Xml.Serialization.XmlTypeAttribute("SourceRootXml", Namespace="urn:shemas-jetbrains-com:installation-data")]
    public enum SourceRootXml
    {
        
        /// <summary>
        /// <para>A directory to which the product is built; contains all of the product binaries. Warning: when doing a local install, this is the same as the target InstallDir.</para>
        /// </summary>
        ProductBinariesDir,
        
        /// <summary>
        /// <para>Home directory of the product, can be used to refer to product library files. Shouldn't be used for the Bin folder, see ProductBinariesDir instead, because it may be redirected on the build.</para>
        /// </summary>
        ProductHomeDir,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1158.0")]
    [System.Xml.Serialization.XmlTypeAttribute("TargetRootXml", Namespace="urn:shemas-jetbrains-com:installation-data")]
    public enum TargetRootXml
    {
        
        /// <summary>
        /// <para>Binaries installation directory on the remote system (the Bin folder).</para>
        /// </summary>
        InstallDir,
    }
    
    /// <summary>
    /// <para>An enumeration of possible macro names, is not used directly in the XML files, but instead serves as a reference info or string constants from the code.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1158.0")]
    [System.Xml.Serialization.XmlTypeAttribute("MacroNameXml", Namespace="urn:shemas-jetbrains-com:installation-data")]
    public enum MacroNameXml
    {
        
        /// <summary>
        /// <para>The System directory. Used to locate the mscoree.dll that is the COM Server for us.</para>
        /// </summary>
        SystemDir,
        
        /// <summary>
        /// <para>The directory that contains the product binaries.</para>
        /// </summary>
        ProductBinariesDir,
        
        /// <summary>
        /// <para>Date and time at the moment the macro is resolved, in an arbitrary format. Use with care, because the date-time might resolve at the installation time on the user machine. The format is not defined.</para>
        /// </summary>
        DateTime,
    }
    
    /// <summary>
    /// <para>A dummy element introduced so that the autogenerated C# sources contained all of the macro name fields, which otherwise will be dropped as unused. Could be used for assigning default values to the macros.</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1158.0")]
    [System.Xml.Serialization.XmlTypeAttribute("MacroXml", Namespace="urn:shemas-jetbrains-com:installation-data")]
    public partial class MacroXml
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("Name")]
        public MacroNameXml Name { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("DefaultValue")]
        public string DefaultValue { get; set; }
    }
}
