/// <copyright company="JetBrains">
/// Copyright © 2003-2008 JetBrains s.r.o.
/// You may distribute under the terms of the GNU General Public License, as published by the Free Software Foundation, version 2 (see License.txt in the repository root folder).
/// </copyright>

// This file was generated by C# Refactory.
// To modify this template, go to Tools/Options/C# Refactory/Code

using System;
using System.IO;
using NUnit.Framework;
using JetBrains.Omea.Containers;
using JetBrains.Omea.COM;

namespace OmniaMeaBaseTests
{
    [TestFixture]
    public class RefCountTests
    {
        [Test]
        public void Test()
        {
            Object_Ref_Counting obj = new Object_Ref_Counting();
            obj.AddRef();
            obj.AddRef();
            obj.AddRef();
            obj.AddRef();
            obj.Release();
            obj.Release();
            obj.Release();
            obj.Release();
            obj.Release();
            obj = null;
        }
    }

}