/*
SPDX-FileCopyrightText: 2003-2008 JetBrains s.r.o.

SPDX-License-Identifier: GPL-2.0-only
*/

#include "nsISupports.idl"

[scriptable, uuid(50dfb942-b1e0-49f7-81e2-b2d0596e5efd)]
interface nsIOmeaConnector : nsISupports
{
  const PRUint32     QM_STOREONLY = 0;
  const PRUint32     QM_RUNOMEA   = 1;
  attribute PRUint32 prop_queue_mode;

  attribute boolean  prop_queue_timer_set;
  attribute boolean  prop_queue_askonexit;

  const PRUint32     CM_EDIT = 0;
  const PRUint32     CM_SAVE = 1;
  attribute PRUint32 prop_clipping_mode;

  readonly attribute boolean omeaInstalled;

  readonly attribute boolean firstRun;

  void loadSettings();
  void storeSettings();

  boolean methodIsSupported( in wstring method );

  void subscribeRSS( in wstring url );
  boolean isSubscribeRSSSupported();

  void createClipping( in boolean silently, in wstring subject, in wstring text, in wstring url );
  boolean isCreateClippingSupported();

  void annotateURL( in wstring url, in wstring title );
  boolean isAnnotateURLSupported();

  void importBookmarks();
};
