// SPDX-FileCopyrightText: 2003-2008 JetBrains s.r.o.
//
// SPDX-License-Identifier: GPL-2.0-only

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
//
using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace JetBrains.Build.AllAssemblies
{
	/// <remarks/>
	[GeneratedCode("xsd", "2.0.50727.1432")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "urn:shemas-jetbrains-com:omea-all-assemblies")]
	[XmlRoot("Project", Namespace = "urn:shemas-jetbrains-com:omea-all-assemblies", IsNullable = false)]
	public partial class AllAssembliesXml
	{
		#region Attributes

		/// <remarks/>
		[XmlElement("ItemGroup")]
		public ItemGroupXml[] ItemGroup { get; set; }

		#endregion
	}

	/// <remarks/>
	[GeneratedCode("xsd", "2.0.50727.1432")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "urn:shemas-jetbrains-com:omea-all-assemblies")]
	public class ItemGroupXml
	{
		#region Attributes

		/// <remarks/>
		[XmlElement("AllAssemblies")]
		public AssemblyXml[] AllAssemblies { get; set; }

		/// <remarks/>
		[XmlElement("References")]
		public ReferenceXml[] References { get; set; }

		#endregion
	}

	/// <remarks/>
	[GeneratedCode("xsd", "2.0.50727.1432")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "urn:shemas-jetbrains-com:omea-all-assemblies")]
	public partial class AssemblyXml
	{
		#region Init

		public AssemblyXml()
		{
			ComRegister = false;
			HasAppConfig = false;
			HasMainfest = false;
			HasXmlSerializers = false;
		}

		#endregion

		#region Attributes

		/// <remarks/>
		[DefaultValue(false)]
		public bool ComRegister { get; set; }

		/// <remarks/>
		[DefaultValue(false)]
		public bool HasAppConfig { get; set; }

		/// <remarks/>
		[DefaultValue(false)]
		public bool HasMainfest { get; set; }

		/// <remarks/>
		[DefaultValue(false)]
		public bool HasXmlSerializers { get; set; }

		/// <remarks/>
		[XmlAttribute]
		public string Include { get; set; }

		/// <remarks/>
		public string MsiGuid { get; set; }

		#endregion
	}

	/// <remarks/>
	[GeneratedCode("xsd", "2.0.50727.1432")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "urn:shemas-jetbrains-com:omea-all-assemblies")]
	public class ReferenceXml
	{
		#region Attributes

		/// <remarks/>
		[XmlAttribute]
		public string Include { get; set; }

		/// <remarks/>
		public string MsiGuid { get; set; }

		#endregion
	}
}
