/// <copyright company="JetBrains">
/// Copyright © 2003-2008 JetBrains s.r.o.
/// You may distribute under the terms of the GNU General Public License, as published by the Free Software Foundation, version 2 (see License.txt in the repository root folder).
/// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace JetBrains.Build.GuidCache
{
	/// <remarks/>
	[GeneratedCode("xsd", "2.0.50727.1432")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "urn:shemas-jetbrains-com:guid-cache")]
	[XmlRoot("GuidCache", Namespace = "urn:shemas-jetbrains-com:guid-cache", IsNullable = false)]
	public partial class GuidCacheXml
	{
		#region Attributes

		/// <remarks/>
		[XmlElement("Loose")]
		public LooseGuidXml[] Loose { get; set; }

		/// <remarks/>
		[XmlElement("Strict")]
		public StrictGuidXml[] Strict { get; set; }

		#endregion
	}

	/// <remarks/>
	[GeneratedCode("xsd", "2.0.50727.1432")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "urn:shemas-jetbrains-com:guid-cache")]
	public partial class StrictGuidXml
	{
		#region Attributes

		/// <remarks/>
		[XmlAttribute]
		public GuidIdXml Id { get; set; }

		/// <remarks/>
		[XmlAttribute]
		public string Value { get; set; }

		#endregion
	}

	/// <remarks/>
	[GeneratedCode("xsd", "2.0.50727.1432")]
	[Serializable]
	[XmlType(Namespace = "urn:shemas-jetbrains-com:guid-cache")]
	public enum GuidIdXml
	{
		/// <remarks/>
		MsiComponent_RegistryData_Hklm,

		/// <remarks/>
		MsiComponent_RegistryData_Hkcu,

		/// <remarks/>
		MsiComponent_RegistryData_Hkmu,

		/// <remarks/>
		MsiComponent_RegistryData_Hkcr,

		/// <remarks/>
		MsiComponent_ProductBinaries_Registry_Hkmu,
	}

	/// <remarks/>
	[GeneratedCode("xsd", "2.0.50727.1432")]
	[Serializable]
	[DebuggerStepThrough]
	[DesignerCategory("code")]
	[XmlType(Namespace = "urn:shemas-jetbrains-com:guid-cache")]
	public partial class LooseGuidXml
	{
		#region Attributes

		/// <remarks/>
		[XmlAttribute]
		public string Name { get; set; }

		/// <remarks/>
		[XmlAttribute]
		public string Value { get; set; }

		#endregion
	}
}