/// <copyright company="JetBrains">
/// Copyright © 2003-2008 JetBrains s.r.o.
/// You may distribute under the terms of the GNU General Public License, as published by the Free Software Foundation, version 2 (see License.txt in the repository root folder).
/// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetBrains.Omea.Jiffa.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Stringtable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stringtable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JetBrains.Omea.Jiffa.Res.Stringtable", typeof(Stringtable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no selection to execute this action upon.
        ///
        ///Please select some resources and try again..
        /// </summary>
        internal static string ActionNoSelection {
            get {
                return ResourceManager.GetString("ActionNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JIRA Server.
        /// </summary>
        internal static string AddJiraServer {
            get {
                return ResourceManager.GetString("AddJiraServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — None —.
        /// </summary>
        internal static string ComponentNone {
            get {
                return ResourceManager.GetString("ComponentNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JIRA Server “{0}” and all of its resources will be deleted.
        ///
        ///Are you sure?.
        /// </summary>
        internal static string ConfirmDeleteServer {
            get {
                return ResourceManager.GetString("ConfirmDeleteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string Credentials {
            get {
                return ResourceManager.GetString("Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete JIRA Server.
        /// </summary>
        internal static string DeleteJiraServer {
            get {
                return ResourceManager.GetString("DeleteJiraServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Don&apos;t Submit —.
        /// </summary>
        internal static string DontSubmit {
            get {
                return ResourceManager.GetString("DontSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The body must not be empty..
        /// </summary>
        internal static string Error_BodyEmpty {
            get {
                return ResourceManager.GetString("Error_BodyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component you&apos;re trying to assign does not belong to the current project..
        /// </summary>
        internal static string Error_ComponentOfWrongProject {
            get {
                return ResourceManager.GetString("Error_ComponentOfWrongProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The issue type you&apos;re tryign to assign does not belong to the current server..
        /// </summary>
        internal static string Error_IssueTypeOfWrongServer {
            get {
                return ResourceManager.GetString("Error_IssueTypeOfWrongServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is more than one parent in the resources hierarchy..
        /// </summary>
        internal static string Error_MultiParent {
            get {
                return ResourceManager.GetString("Error_MultiParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no parent in the resources hierarchy..
        /// </summary>
        internal static string Error_NoParent {
            get {
                return ResourceManager.GetString("Error_NoParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no project with the given key..
        /// </summary>
        internal static string Error_NoProjectByKey {
            get {
                return ResourceManager.GetString("Error_NoProjectByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The priority you&apos;re tryign to assign does not belong to the current server..
        /// </summary>
        internal static string Error_PriorityOfWrongServer {
            get {
                return ResourceManager.GetString("Error_PriorityOfWrongServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status you&apos;re tryign to assign does not belong to the current server..
        /// </summary>
        internal static string Error_StatusOfWrongServer {
            get {
                return ResourceManager.GetString("Error_StatusOfWrongServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title must not be empty..
        /// </summary>
        internal static string Error_TitleEmpty {
            get {
                return ResourceManager.GetString("Error_TitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified parent object does not correspond to the Resources hierarchy..
        /// </summary>
        internal static string Error_WrongParent {
            get {
                return ResourceManager.GetString("Error_WrongParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Go to JIRA tab and add a JIRA Server —.
        /// </summary>
        internal static string GotoTabAddServer {
            get {
                return ResourceManager.GetString("GotoTabAddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIRA.
        /// </summary>
        internal static string Jira {
            get {
                return ResourceManager.GetString("Jira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIRA Server Properties….
        /// </summary>
        internal static string JiraServerProperties {
            get {
                return ResourceManager.GetString("JiraServerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} – JIRA Server Properties.
        /// </summary>
        internal static string JiraServerPropertiesTitle {
            get {
                return ResourceManager.GetString("JiraServerPropertiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no JIRA projects available. Please go to the JIRA tab and add a JIRA server..
        /// </summary>
        internal static string NoJiraProjects {
            get {
                return ResourceManager.GetString("NoJiraProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a JIRA project from the combo box..
        /// </summary>
        internal static string SelectJiraProject {
            get {
                return ResourceManager.GetString("SelectJiraProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Auto —.
        /// </summary>
        internal static string StatusAuto {
            get {
                return ResourceManager.GetString("StatusAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no JIRA project specified for submitting the issues into.
        ///
        ///Please go to the Jiffa options page and chose a project. Before that, a JIRA server must be configured on the JIRA tab..
        /// </summary>
        internal static string SubmitProjectNotSpecified {
            get {
                return ResourceManager.GetString("SubmitProjectNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains the JIRA Submitter options..
        /// </summary>
        internal static string SubmitterOptionsPanePrompt {
            get {
                return ResourceManager.GetString("SubmitterOptionsPanePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit to JIRA….
        /// </summary>
        internal static string SubmitToJira {
            get {
                return ResourceManager.GetString("SubmitToJira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing the “{0}” JIRA server….
        /// </summary>
        internal static string SyncingJiraServer {
            get {
                return ResourceManager.GetString("SyncingJiraServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to synchronize the “{0}” JIRA server..
        /// </summary>
        internal static string SyncingJiraServerFailed {
            get {
                return ResourceManager.GetString("SyncingJiraServerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done synchronizing the “{0}” JIRA server..
        /// </summary>
        internal static string SyncingJiraServerSucceeded {
            get {
                return ResourceManager.GetString("SyncingJiraServerSucceeded", resourceCulture);
            }
        }
    }
}
